# Generated by Django 4.2.9 on 2024-01-28 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_shortenedurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='expired_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 8, 44, 12, 285711, tzinfo=datetime.timezone.utc)),
        ),
    ]
