# Generated by Django 4.2.9 on 2024-01-28 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_shortenedurl_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='expired_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 8, 50, 27, 618568, tzinfo=datetime.timezone.utc)),
        ),
    ]
